config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :books, only: [:index, :show, :new, :create]

  resources :readings, only: [:index, :show, :new, :create, :update]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  has_many :readings
end

app/models/reading.rb
class Reading < ApplicationRecord
  belongs_to :book
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :readings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  BOOK_CATEGORIES = ['Travel', 'Fantastic', 'Historic', 'Thriller', 'Self-Development', 'Children']
  LANGUAGES = ['English', 'French', 'German', 'Spanish', 'Chinese', 'Arabic']

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :find_book, only: [:show]

  def index
    @books = Book.all
  end

  def show  
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to book_path(@book)
    else
      render :new
    end
  end

  private

  def find_book
    @book = Book.find(params[:id])
  end

  def book_params
    params.require(:book).permit([:title, :author, :description, :category, :language])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/readings_controller.rb
class ReadingsController < ApplicationController
  before_action :find_book, only: [:new, :create]
  before_action :find_reading, only: [:show]

  def index
    @readings = Reading.all
  end

  def show
  end

  def new
    @reading = Reading.new
  end

  def create
    @reading = reading.new(reading_params)
    if @reading.save
      redirect_to reading_path(@reading)
    else
      render :new
    end
  end

  def update
  end

  private

  def find_book
    @book = Book.find(params[:book_id])
  end

  def find_reading
    @reading = Reading.find(params[:id])
  end

  def reading_params
    params.require(:reading).permit(:start_date, :end_date, :rating, :status)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/books/create.html.erb
<h1>Books#create</h1>
<p>Find me in app/views/books/create.html.erb</p>

app/views/books/index.html.erb
<div class="container mt-4">
  <!-- browse buttons -->

  <p>Add button for new book w/ link</p>
  

  <div class="d-flex justify-content-around">
    <% unless @category == "all" %>
      <%= link_to "All", books_path, class: 'btn btn-ghost' %>
    <% end %>
    <% ApplicationController::BOOK_CATEGORIES.each do |category| %>
      <%= link_to category, books_path(category: category), class: "btn btn-ghost#{'-selected' if params[:category] == category}" %>
    <% end %>
  </div>
  <h3 class="mt-4 mb-2 ml-3" id="index_title">Books</h3>
  <div class="container">
    <div class="row">
      <div class="col-4">
        <% @books.each do |book| %>
          <div class="card-product mt-2" data-book-id="<%= book.id %>">
            <div class="card-product-infos">
              <h2><%= link_to book.title, book_path(book) %></h2>
              <p><%= book.description %></p>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
<p>Made by Maxence Luneau</p>

app/views/books/new.html.erb
<h1>Books#new</h1>
<p>Find me in app/views/books/new.html.erb</p>

<div class="container">
  <%= simple_form_for @book, url: books_path do |f| %>
    <%= f.input :title %>
    <%= f.input :author %>
    <%= f.input :description %>
    <%= f.input :category, collection: ApplicationController::BOOK_CATEGORIES %>
    <%= f.input :language, collection: ApplicationController::LANGUAGES %>
    <%= f.submit %>
  <% end %>
</div>

app/views/books/show.html.erb
<div class="container mx-20 mt-4">

  <div class="d-flex justify-content-around" >
    <div class="mr-4">
      <h2 class="mt-1"><%= @book.title %>  </h2>
      
        <div class="card-book-infos">
          <div>
            <p><strong>Author:</strong> <%= @book.author %></p>
            <p><strong>Title:</strong> <%= @book.title %></p>
            <p><strong>Description:</strong> <%= @book.description %></p>
            <p><strong>Category:</strong> <%= @book.category %></p>
            <p><strong>Language:</strong> <%= @book.language %></p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookTracker - Track your reads in 2021</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>

    <!-- Hotjar Tracking Code for www.certif-mluneau.xyz -->
    <script>
      (function(h,o,t,j,a,r){
        h.hj=h.hj||function(){(h.hj.q=h.hj.q||[]).push(arguments)};
        h._hjSettings={hjid:2288568,hjsv:6};
        a=o.getElementsByTagName('head')[0];
        r=o.createElement('script');r.async=1;
        r.src=t+h._hjSettings.hjid+j+h._hjSettings.hjsv;
        a.appendChild(r);
      })(window,document,'https://static.hotjar.com/c/hotjar-','.js?sv=');
    </script>

  </head>

  <body>
    <%= render 'shared/flashes' %>

    <%= yield %>

    <%= render 'shared/navbar' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="background">
  <h1>Welcome to Booktracker</h1>
  <p>Find me in app/views/pages/home.html.erb</p>

  <p>Need to rearrage the design, card categories linked to different features for the app</p>
  Clean css for the homepage.
  Link everything coded so the user only has books to his name.
</div>

app/views/readings/create.html.erb
<h1>Readings#create</h1>
<p>Find me in app/views/readings/create.html.erb</p>

app/views/readings/index.html.erb
<h1>Please find your readings here (list):</h1>

<ul>To do:</ul>
  <li>Order by ratings</li>
  <li>Reading atm first</li>

app/views/readings/new.html.erb
<h1>Readings#new</h1>
<p>Find me in app/views/readings/new.html.erb</p>

<div class="d-flex justify-content-center mt-10">
  <%= simple_form_for [@book, @reading] do |f| %>
    <%= f.input :start_date, as: :hidden, input_html: {id: "range_start", style: "display: none;"} %>
    <%= f.input :end_date, as: :hidden, input_html: {id: "range_end"}%>
    <%= f.input :rating, as: range_start: 1, range_end: 10 %>
    <%= f.submit  class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/readings/show.html.erb
<h1>Readings#show</h1>
<p>Find me in app/views/readings/show.html.erb</p>

app/views/readings/update.html.erb
<h1>Readings#update</h1>
<p>Find me in app/views/readings/update.html.erb</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<%# MOBILE NAVBAR %>

<div id="content-mobile">
  <div class="navbar-mobile">
    <div class=navbar-container>
    <span>
      <a href="#" class="navbar-item <%= 'active' if controller_name == 'transactions' %>">
        <i class="fas fa-list-ul"></i>
        <%#= image_tag "icons/history", alt: "alttext" %>
        <!-- <div class="icon history green"></div> -->
        Historique
      </a>
      <a href="#" class="navbar-item <%= 'active' if controller_name == 'discussions' %>">
        <%# <svg xmlns="http://www.w3.org/2000/svg" width="35" height="35" viewBox="0 0 24 24" fill="none" stroke="#6F6E80" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z"></path></svg> %>
        <i class="far fa-comment-alt"></i>
        Messages
      </a>
    </span>
    <span>
      <a href="#" class="navbar-item <%= 'active' if controller_name == 'articles' %>">
        <%# <svg xmlns="http://www.w3.org/2000/svg" width="35" height="35" viewBox="0 0 24 24" fill="none" stroke="#6F6E80" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"></path><circle cx="12" cy="12" r="3"></circle></svg> %>
        <i class="far fa-eye"></i>
        Articles
      </a>
      <a href="#" class="navbar-item <%= 'active' if controller_name == 'pages' %>">
        <%# <svg xmlns="http://www.w3.org/2000/svg" width="35" height="35" viewBox="0 0 24 24" fill="none" stroke="#6F6E80" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2"></path><circle cx="12" cy="7" r="4"></circle></svg> %>
        <i class="far fa-user"></i>
        Profil
      </a>
    </span>
    </div>
  </div>
</div>